# workflow name
name: Deploy To Github Pages

# 当有 push 到仓库和外部触发的时候就运行 [push, repository_dispatch]
on: [push, repository_dispatch]

# YUQUE_TOKEN
# SSH_PRIVATE_KEY
jobs:
  deploy: 
    name: 部署我的博客内容
    runs-on: ubuntu-latest 
    env:
      TZ: Asia/Shanghai    
        
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@main 
      
    # from: https://github.com/actions/setup-node  
    - name: Setup Node.js 10.x 
      uses: actions/setup-node@main
      with:
        node-version: "15.x"
    
    # from https://github.com/x-cold/yuque-hexo
    - name: sync
      env:
        YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
      run: |
        rm -rf package-lock.json
        rm -rf yuque.json
        npm install yuque-hexo -g
        npm install
        yuque-hexo sync
    
    # git clone https://github.com/aouoxx/aouoxx.github.io.git deploy_git
       # mv ./deploy_git/.git ./public/
       # cd ./public
    - name: deploy 
      run: |
        rm -rf package-lock.json
        rm -rf yuque.json
        git config user.name "aouoxx"
        git config user.email "aouo1987@163.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --
